name: game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# ---------- PACKAGES ----------
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.4
  smooth_page_indicator: ^1.1.0
  flutter_localization: ^0.2.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

# State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.5

  #Custom Game Dependencies
  shared_preferences: ^2.0.13
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  # ---------- LOCAL ASSETS ----------
  assets:
    - assets/images/
    - lib/l10n/

  # ---------- LOCAL FONTS ----------
  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: assets/fonts/Rajdhani-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 800
